# Spring
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hikariy?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    connection-timeout: 30000
    connection-init-sql: 2
    maximum-pool-size: 20
    minimum-idle: 0
    connection-test-query: SELECT 1
    idle-timeout: 600000
    max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
server:
  port: 8080
#  servlet:
#    context-path: /hikariy